# Каталог для мониторинга
MONITOR_DIR="/tmp"
#"/usr/local/"

# Адрес получателя email (можно несколько через запятую)
EMAIL_TO="katezaytsewa@gmail.com, jekaterinazz@yandex.ru"

# Тема письма
EMAIL_SUBJECT="File Monitor Alert"

# Критерии
REGEX='^virus\.com$'
SIZE=102400

# MD5-суммы через пробел (одна или несколько, может быть пустым)
MD5='a8d8e05598f07a83e85bca06f20b5f61'
MD5='d41d8cd98f00b204e9800998ecf8427e'
MD5='098f6bcd4621d373cade4e832627b4f6'